---
title: "create_output_sevfreq"
output: html_document
---

Load benchmarks
```{r}
bmr_freq01 = readRDS("output/bmr_freq01.rds")
bmr_sev01 = readRDS("output/bmr_sev01.rds")
bmr_pcc01 = readRDS("output/bmr_pcc01.rds")
```

```{r}
bmr_freq01_plot <- autoplot(bmr_freq01)
bmr_sev01_plot <- autoplot(bmr_sev01)
bmr_pcc01_plot <- autoplot(object = bmr_pcc01, measure = measure_acc)
```

```{r}
ggsave(bmr_freq01_plot, file = "output/grafics/bmr_freq01_plot.pdf")
ggsave(bmr_sev01_plot, file = "output/grafics/bmr_sev01_plot.pdf")
ggsave(bmr_pcc01_plot, file = "output/grafics/bmr_pcc01_plot.pdf")
```

```{r}
agg_bmr_freq01 = bmr_freq01$aggregate(measure_mse)
bmr_freq01_table = tibble(
  learner = agg_bmr_freq01$learner_id,
  mse = agg_bmr_freq01$regr.mse
)
print(
  xtable(bmr_freq01_table),
  include.rownames = FALSE
)
```
```{r}
agg_bmr_sev01 = bmr_sev01$aggregate(measure_mse)
bmr_sev01_table = tibble(
  learner = agg_bmr_sev01$learner_id,
  mse = agg_bmr_sev01$regr.mse
)
print(
  xtable(bmr_sev01_table),
  include.rownames = FALSE
)
```
```{r}
agg_bmr_pcc01 = bmr_pcc01$aggregate(measure_acc)
bmr_pcc01_table = tibble(
  learner = agg_bmr_pcc01$learner_id,
  mse = agg_bmr_pcc01$classif.acc
)
print(
  xtable(bmr_pcc01_table),
  include.rownames = FALSE
)
```



