---
title: "03_02_final_sev_freq"
output: html_document
---

```{r}
splits = readRDS("output/true_split.rds")
```

```{r}
mv_data_eval <- mv_data_imp
  
date_cols <- mv_data_eval %>%
select(where(is.Date)) %>%
colnames()

mv_data_eval <- mv_data_eval %>%
    mutate(across(all_of(date_cols), ~ year(.x), .names = "{.col}_year")) %>%
    mutate(across(all_of(date_cols), ~ month(.x), .names = "{.col}_month")) %>%
    mutate(across(all_of(date_cols), ~ day(.x), .names = "{.col}_day"))

mv_data_eval <- mv_data_eval %>% 
  select(-c(Date_start_contract, Date_last_renewal)) 

mv_data_eval_train <- mv_data_eval %>% 
  filter(ID %in% splits$train_ids) %>% 
  select(-c(N_claims_year, N_claims_history, R_Claims_history, ID))

mv_data_eval_test_X <- mv_data_eval %>% 
  filter(ID %in% splits$test_ids) %>% 
  select(-c(N_claims_year, N_claims_history, R_Claims_history, Cost_claims_year, ID))
mv_data_eval_test_Y <- mv_data_eval %>%
  filter(ID %in% splits$test_ids) %>% 
  pull(Cost_claims_year)
```


```{r}
task_freq_train <- df_agg %>% 
  filter(PCC == "1" & ID %in% splits$train_ids) %>% 
  select(-c(PCC, Avg_claims, ID, claims_exposure)) %>% 
  TaskRegr$new(id = "freq_train", backend = ., target = "Freq")

task_freq_train$set_col_roles("Total_exposure", roles = "weight")

task_freq_test <- df_agg %>%
  filter(ID %in% splits$test_ids) %>%
  select(-c(PCC, Avg_claims, ID, claims_exposure)) %>%
  TaskRegr$new(id = "freq_test", backend = ., target = "Freq")

task_freq_test$set_col_roles("Total_exposure", roles = "weight")
```

```{r}
task_sev_train <- df_agg %>% 
  filter(PCC == "1" & ID %in% splits$train_ids) %>% 
  select(-c(PCC, Freq, ID, claims_exposure)) %>% 
  TaskRegr$new(
  id = "Severity_train",
  backend = .,
  target = "Avg_claims"
)

task_sev_train$set_col_roles("Total_exposure", roles = "weight")

task_sev_test <- df_agg %>% 
  filter(ID %in% splits$test_ids) %>% 
  select(-c(PCC, Freq, ID, claims_exposure)) %>% 
  TaskRegr$new(
  id = "Severity_test",
  backend = .,
  target = "Avg_claims"
)

# Sæt vægtkolonne
task_sev_test$set_col_roles("Total_exposure", roles = "weight")
```

```{r}
mv_data_pcc <- df_agg %>% select(-Freq, -Avg_claims, -ID, -claims_exposure)

task_pcc = TaskClassif$new(id = "pcc_est", backend = mv_data_pcc, target = "PCC", positive = "1")

# Set a column as the weight column
task_pcc$set_col_roles(cols = "Total_exposure", roles = "weight")
```

```{r}
task_featureless <- mv_data_eval_train %>% 
  TaskRegr$new(
  id = "featureless",
  backend = .,
  target = "Cost_claims_year"
)

task_featureless$set_col_roles("Exposure", roles = "weight")
```


```{r}
# set.seed(1234)
# split = partition(task_pcc, ratio = 0.8)
# 
# true_split = list(
#   test_nr = split$test,
#   train_nr = split$train,
#   test_ids = as.numeric(df_agg$ID[split$test]),
#   train_ids = as.numeric(df_agg$ID[split$train])
# 
# )
# saveRDS(true_split, file = "output/true_split.rds")
```


```{r}
resampling_inner   = rsmp("cv", folds = 2)
measure_mse        = msr("regr.mse")
measure_acc = msr("classif.acc")
measure_mae = msr("regr.mae")
tuner_rs           = tnr("random_search")
terminator_evals = trm("evals", n_evals = 500)
```

Setting up pipeline:
```{r}
# Define your encoding pipe
pipe_encode = po("encode",
  method         = "treatment",
  affect_columns = selector_type("factor")
)

# Helper to wrap any learner in your pipe
make_graph_learner = function(learner) {
  gl = pipe_encode %>>% learner
  GraphLearner$new(gl)
}
```

Setup leaner freq:

```{r}
base_lgbm = mlr3extralearners::lrn("regr.lightgbm",
                                   learning_rate = to_tune(0.005, 0.1, logscale = TRUE),
                                   num_leaves = to_tune(10, 512),
                                   max_depth = to_tune(3, 15),
                                   feature_fraction = to_tune(0.6, 1.0),
                                   bagging_fraction = to_tune(0.6, 1.0))

gl_lgbm   = make_graph_learner(base_lgbm)

at_lgbm   = AutoTuner$new(
  learner      = gl_lgbm,
  resampling   = resampling_inner,
  measure      = measure_mse,
  tuner        = tuner_rs,
  terminator   = terminator_evals        # pulls the xgboost‐space, namespaced
)
```

Setup leaner sev:

```{r}
gl_ridge = make_graph_learner(
  lrn("regr.glmnet", id = "ridge", alpha = 0)
)
```

Setup leaner pcc:

```{r}
base_lgbm_pcc = mlr3extralearners::lrn("classif.lightgbm",
  learning_rate = to_tune(0.005, 0.1, logscale = TRUE),
  num_leaves = to_tune(10, 512),
  max_depth = to_tune(3, 15),
  feature_fraction = to_tune(0.6, 1.0),
  bagging_fraction = to_tune(0.6, 1.0),
  predict_type = "prob")

gl_lgbm_pcc   = make_graph_learner(base_lgbm_pcc)

at_lgbm_pcc   = AutoTuner$new(
  learner      = gl_lgbm_pcc,
  resampling   = resampling_inner,
  measure      = measure_acc,
  tuner        = tuner_rs,
  terminator   = terminator_evals        
)
```
test
```{r}
gl_featless = make_graph_learner(lrn("regr.featureless"))
```


train models:
```{r}
at_lgbm$train(task_freq_train) # freq 
gl_ridge$train(task_sev_train) # sev
at_lgbm_pcc$train(task_pcc, row_ids = splits$train_nr) # pcc
gl_featless$train(task_featureless)
```

```{r}
pred_freq = at_lgbm$predict_newdata(mv_data_eval_test_X %>% rename(Total_exposure = Exposure))
pred_sev  = gl_ridge$predict_newdata(mv_data_eval_test_X %>% rename(Total_exposure = Exposure))
pred_pcc = at_lgbm_pcc$predict_newdata(mv_data_eval_test_X %>% rename(Total_exposure = Exposure))

pred_cc = pred_freq$response*pred_sev$response*pred_pcc$prob[,1]

pred_fl <- gl_featless$predict_newdata(mv_data_eval_test_X)$response

MSE_fl <- mean((pred_fl - mv_data_eval_test_Y)^2)
MSE_sf <- mean((pred_cc - mv_data_eval_test_Y)^2)
```

