---
title: "AggregeretData"
output: html_document
---
```{r}
knitr::knit(
  text  = readLines("01_01_EDA.Rmd"),
  quiet = TRUE,
  envir = globalenv()
)
```

```{r}
df_agg <- mv_data_imp %>%
  group_by(ID) %>%
  summarise(
    # Sidste værdi i historikken (baseret på rækkefølge i datasættet)
    Date_start_contract  = first(Date_start_contract),
    Date_last_renewal = last(Date_last_renewal),
    Distribution_channel = last(Distribution_channel),
    Seniority = last(Seniority),
    Policies_in_force = last(Policies_in_force),
    Max_policies = last(Max_policies),
    Max_products = last(Max_products),
    Payment = last(Payment),
    #N_claims_year = last(N_claims_year),
    N_claims_history = last(N_claims_history),
    R_Claims_history = last(R_Claims_history),
    Type_risk = last(Type_risk),
    Area = last(Area),
    Second_driver = last(Second_driver),
    Power = last(Power),
    Cylinder_capacity = last(Cylinder_capacity),
    Value_vehicle = last(Value_vehicle),
    N_doors = last(N_doors),
    Type_fuel = last(Type_fuel),
    Weight = last(Weight),
    Age = last(Age),
    Age_driving_licence = last(Age_driving_licence),
    Vehicle_age = last(Vehicle_age),
    # Summerede værdier
    Total_N_claims_year = sum(N_claims_year, na.rm = TRUE),
    Total_premium = sum(Premium, na.rm = TRUE),
    Total_claims = sum(Cost_claims_year, na.rm = TRUE),
    Total_exposure = sum(Exposure, na.rm = TRUE)
  )
```

```{r}
df_agg_tmp <- df_agg %>%
  mutate(
    PCC = as.factor(ifelse(Total_claims > 0, "1", "0")),
    Freq = Total_N_claims_year / Total_exposure,
    Avg_claims = Total_claims / Total_N_claims_year
    )
```

```{r}
mv_changed_data <- df_agg_tmp %>%
  select(-c(Total_N_claims_year, Total_premium, Total_claims, R_Claims_history))

date_cols <- mv_changed_data %>%
  select(where(is.Date)) %>%
  colnames()

mv_changed_data <- mv_changed_data %>%
    mutate(across(all_of(date_cols), ~ year(.x), .names = "{.col}_year")) %>%
    mutate(across(all_of(date_cols), ~ month(.x), .names = "{.col}_month")) %>%
    mutate(across(all_of(date_cols), ~ day(.x), .names = "{.col}_day"))

df_agg <- mv_changed_data %>%
  select(-c(Date_start_contract, Date_last_renewal, N_claims_history))
```

```{r}
df_agg_P <- df_agg %>%
  filter(PCC == "1")
```

